---
- name: Add int to VLAN
  hosts: ciscodevice
  become_method: enable
  gather_facts: no
  connection: local
  #connection: network_cli

  tasks:
  - name: Ping Test
    ios_ping:
      dest: 172.16.8.71 

  - name: Configure Provider
    set_fact:
      provider:
        username: kalpesh
        password: charusat

  - name: Create vlan
    ios_vlan:
      vlan_id: 17
      name: WDS
      state: present

  - name: Add interfaces to VLAN
    ios_vlan:
      vlan_id: 17
      interfaces:
        - GigabitEthernet1/0/1
        - GigabitEthernet1/0/2
        - GigabitEthernet1/0/3
        - GigabitEthernet1/0/4
        - GigabitEthernet1/0/5
        - GigabitEthernet1/0/6
        - GigabitEthernet1/0/7
        - GigabitEthernet1/0/8
        - GigabitEthernet1/0/9
        - GigabitEthernet1/0/10
        - GigabitEthernet1/0/11
        - GigabitEthernet1/0/12
        - GigabitEthernet1/0/13
        - GigabitEthernet1/0/14
        - GigabitEthernet1/0/15
        - GigabitEthernet1/0/16
        - GigabitEthernet1/0/17
        - GigabitEthernet1/0/18
        - GigabitEthernet1/0/19
        - GigabitEthernet1/0/20
        - GigabitEthernet1/0/21
        - GigabitEthernet1/0/22
        - GigabitEthernet1/0/23
        
  - name: Check if interfaces is assigned to VLAN
    ios_vlan:
      vlan_id: 17
      associated_interfaces:
        - GigabitEthernet1/0/1
        - GigabitEthernet1/0/2
        - GigabitEthernet1/0/3
        - GigabitEthernet1/0/4
        - GigabitEthernet1/0/5
        - GigabitEthernet1/0/6
        - GigabitEthernet1/0/7
        - GigabitEthernet1/0/8
        - GigabitEthernet1/0/9
        - GigabitEthernet1/0/10
        - GigabitEthernet1/0/11
        - GigabitEthernet1/0/12
        - GigabitEthernet1/0/13
        - GigabitEthernet1/0/14
        - GigabitEthernet1/0/15
        - GigabitEthernet1/0/16
        - GigabitEthernet1/0/17
        - GigabitEthernet1/0/18
        - GigabitEthernet1/0/19
        - GigabitEthernet1/0/20
        - GigabitEthernet1/0/21
        - GigabitEthernet1/0/22
        - GigabitEthernet1/0/23
#        - GigabitEthernet1/0/7
#        - GigabitEthernet1/0/10
