---
- name: Change Bios Boot Order of Remote PC
  hosts: 715A
  gather_facts: no
  become_method: runas

  vars:
    ansible_become_password: ceit

  tasks:
  - name: ping
    win_ping:

  - name: Remove BCU folder if Exist
    win_shell: rm -r c:\BCU | out-null
    ignore_errors: yes
    become: yes
    become_user: Administrator

  - name: Make BCU Directory
    win_shell: mkdir c:\BCU
    ignore_errors: yes

  - name: Copy BiosConfigurationUtility
    win_shell: wget http://wdsserver:8080/BiosConfigUtility64.exe -OutFile C:\bcu\BiosConfigUtility64.exe

  - name: Copy config File
    win_shell: wget http://wdsserver:8080/Config/HPBiosConfigHDDFirst.txt -OutFile C:\bcu\HPBiosConfigHDDFirst.txt
 

  - name: Configure Bios of Remote PC
    win_shell: C:\bcu\BiosConfigUtility64.exe /Set:c:\bcu\HPBiosConfigHDDFirst.txt
    ignore_errors: yes
    become: yes
    become_user: Administrator

  - name: Remove BCU folder
    win_shell: rm -r c:\BCU | out-null
    ignore_errors: yes
    become: yes
    become_user: Administrator


  - name: Reboot Computer
    win_shell: shutdown -r -f -t 00
    become: yes
    become_user: Administrator   
