---
- name: Charusat Service
  hosts: FYECLAB2
  gather_facts: no
  tasks:

  - name: ping
    win_ping:

  - name: Reset Password
    win_shell: Net user CharusatApps password

  - name: Start Charusat Service
    win_shell: Get-service CharusatApps | Start-service
  
  - name: CharusatApps Service to Manual
    win_shell: Set-Service CharusatApps -StartupType Manual

  - name: WinRM Service to Manual
    win_shell: Set-Service CharusatApps -StartupType Manual

  - name: WinRM Service to Manual
    win_shell: Set-Service winRM -StartupType Manual

  - name: WinRM Service to Automatic
    win_shell: Set-Service winRM -StartupType Automatic

