---
- name: MATLAB 2021b
  hosts: [715A]
  gather_facts: no

  vars:
    ansible_become_user: Administrator
    ansible_become_pass: password

  tasks:

  - name: ping
    win_ping:

  - name: Copy MATLAB PS1 file
    win_get_url:
      url: http://172.16.12.244:8080/Matlab2021b.ps1
      dest: C:\
    
  - name: MATLAB Install Script Run
    win_shell:  C:\Matlab2021b.ps1
    become: yes
    become_method: runas

